# Name of this workflow
name: pull-requests

# Configure action events that trigger this workflow
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

# Configure jobs this workflow consists of
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Workspace
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended by SonarCloud for improved relevancy of reporting
          fetch-depth: 0

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build
        run: mvn -B -e -V -T1 install -DskipTests=true

      - name: Unit Test
        run: mvn -B -e -V -T1 surefire:test

      - name: Integration Test
        run: >-
          mvn -B -e -V -T1 failsafe:integration-test
            -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url="https://sonarcloud.io" -Dsonar.organization=fschrogl-fsdev

      - name: Code Analysis
        run: mvn -B -e -V -T1 sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
